language: c
compiler:
  - gcc
  - clang

env:
  - PLATFORM=posix TESTS=yes TLS=no
  - PLATFORM=posix TLS=openssl
  - PLATFORM=contiki TLS=no
  - PLATFORM=lwip TLS=no

addons:
  apt_packages:
    - pkg-config
    - graphviz
    - libcunit1-dev
    - doxygen
    - libxml2-utils
    - xsltproc
    - docbook-xml
    - docbook-xsl
    - asciidoc

branches:
  only:
     - master
     - develop
     - /^release-.*$/
     - travis-test

before_script: ./autogen.sh --clean && ./autogen.sh

script: scripts/build.sh
