sudo: required

services:
  - docker

env:
  - PLATFORM=posix TESTS=yes TLS=no
  - PLATFORM=posix TLS=openssl
#  - PLATFORM=contiki TLS=no
#  - PLATFORM=lwip TLS=no

before_install:
  - docker build -t obgm/libcoap:travis-env .

branches:
  only:
     - master
     - develop
     - /^release-.*$/
     - travis-test

script:
  - docker run obgm/libcoap:travis-env /bin/sh -c "./configure --disable-documentation --enable-tests --enable-examples --with-openssl && make"
